# Filtrado 8
Consiste en sacar las dwas, asociadas a tareas y ocupaciones. Paso 1: traduccion de ocupacion a dwas. Lista de dwas also.

## SQL

In [5]:
# -*- coding: utf-8 -*-
from pathlib import Path

# Lista tal como la diste
ocupations = [
    'Industrial Production Managers','Quality Control Systems Managers','Supply Chain Managers',
    'Human Resources Managers','Logistics Engineers','Bioengineers and Biomedical Engineers',
    'Chemical Engineers','Validation Engineers','Manufacturing Engineers','Mechanical Engineers',
    'Automotive Engineers','Mechatronics Engineers','Robotics Engineers','Robotics Technicians',
    'Industrial Engineering Technologists and Technicians',
    'Mechanical Engineering Technologists and Technicians',
    'Biochemists and Biophysicists','Microbiologists','Chemists'
]

In [6]:

# Carpeta de salida (cámbiala si quieres)
OUT_DIR = Path("filtrado8")
OUT_DIR.mkdir(parents=True, exist_ok=True)

TEMPLATE = """USE onet;

SELECT
  o.onetsoc_code,
  o.title,
  td.task_id,
  t.task,
  td.dwa_id,
  dwaref.dwa_title
FROM tasks_to_dwas td
JOIN occupation_data o ON td.onetsoc_code = o.onetsoc_code
JOIN dwa_reference dwaref ON td.dwa_id = dwaref.dwa_id
JOIN task_statements t ON td.task_id = t.task_id
WHERE o.title = '{title_escaped}';
"""

In [7]:

for title in ocupations:
    # title=title.lower()
    # Escapar comillas simples para SQL (por si en el futuro aparece alguna)
    title_escaped = title.replace("'", "''")
    # Nombre de archivo: espacios -> _
    filename = title.replace(" ", "_") + ".sql"
    sql_text = TEMPLATE.format(title_escaped=title_escaped)
    (OUT_DIR / filename).write_text(sql_text, encoding="utf-8")

print(f"Generados {len(ocupations)} archivos .sql en: {OUT_DIR.resolve()}")

Generados 19 archivos .sql en: /Users/jpardo/Desktop/Proyectos/AI4LABOUR/Mejoras/eerr/filtrado8

## Agrupacion de todos los datasets

In [8]:
import os
import pandas as pd

path = "/Users/jpardo/Desktop/Proyectos/AI4LABOUR/mejoras/eerr/filtrado8"

# Listar solo CSV
archivos = [i for i in os.listdir(path) if i.endswith('.csv')]

dfs = []  # lista para acumular dataframes

for i in archivos:
    path_archivo = os.path.join(path, i)
    df_temp = pd.read_csv(path_archivo)
    df_temp["archivo_origen"] = i  # opcional: para saber de qué archivo viene cada fila
    dfs.append(df_temp)

# Unir todos los DataFrames
df_final = pd.concat(dfs, ignore_index=True)

print(f"Se han cargado {len(df_final)} filas de {len(archivos)} archivos.")

Se han cargado 560 filas de 19 archivos.

In [9]:
display(df_final)

,onetsoc_code,title,task_id,task,dwa_id,dwa_title,archivo_origen
0,17-2141.02,Automotive Engineers,16421,"Read current literature, attend meetings or co...",4.A.2.b.3.I01.D20,Update technical knowledge.,Automotive_Engineers.csv
1,17-2141.02,Automotive Engineers,16422,Establish production or quality control standa...,4.A.2.b.2.I07.D06,Determine operational criteria or specifications.,Automotive_Engineers.csv
2,17-2141.02,Automotive Engineers,16423,Prepare or present technical or project status...,4.A.3.b.6.I15.D04,Prepare operational reports.,Automotive_Engineers.csv
3,17-2141.02,Automotive Engineers,16424,Develop or implement operating methods or proc...,4.A.2.b.1.I09.D06,Implement design or process improvements.,Automotive_Engineers.csv
4,17-2141.02,Automotive Engineers,16424,Develop or implement operating methods or proc...,4.A.2.b.4.I03.D14,Develop technical methods or processes.,Automotive_Engineers.csv
...,...,...,...,...,...,...,...
555,11-3051.01,Quality Control Systems Managers,15428,Analyze quality control test results and provi...,4.A.2.a.4.I07.D12,Analyze data to inform operational decisions o...,Quality_Control_Systems_Managers.csv
556,11-3051.01,Quality Control Systems Managers,15428,Analyze quality control test results and provi...,4.A.4.a.2.I03.D14,Confer with organizational members to accompli...,Quality_Control_Systems_Managers.csv
557,11-3051.01,Quality Control Systems Managers,15429,"Oversee workers including supervisors, inspect...",4.A.4.b.4.I01.D13,Supervise employees.,Quality_Control_Systems_Managers.csv
558,11-3051.01,Quality Control Systems Managers,15430,Monitor performance of quality control systems...,4.A.1.a.2.I02.D05,Monitor organizational procedures to ensure pr...,Quality_Control_Systems_Managers.csv
559,11-3051.01,Quality Control Systems Managers,15431,Direct product testing activities throughout p...,4.A.4.b.4.I08.D03,Manage control system activities in organizati...,Quality_Control_Systems_Managers.csv

In [10]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /Users/jpardo/anaconda3/envs/iaa_teresia/lib/python3.11/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /Users/jpardo/anaconda3/envs/iaa_teresia/lib/python3.11/site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip install --upgrade pip

In [11]:
# Cargar el Excel
ruta_excel = "/Users/jpardo/Desktop/Proyectos/AI4LABOUR/mejoras/eerr/Jobs List ICBE.xlsx"
df_excel = pd.read_excel(ruta_excel, sheet_name="ICBE")
# Pasar nombres de columnas a minúsculas
df_excel.columns = df_excel.columns.str.lower()


display(df_excel)

,o.net.soc.code,title,icbe,description
0,11-3051.00,Industrial Production Managers,Primary,"Plan, direct, or coordinate the work activitie..."
1,11-3051.01,Quality Control Systems Managers,Secondary,"Plan, direct, or coordinate quality assurance ..."
2,11-3071.04,Supply Chain Managers,Secondary,"Direct or coordinate production, purchasing, w..."
3,11-3121.00,Human Resources Managers,Secondary,"Plan, direct, or coordinate human resources ac..."
4,13-1081.01,Logistics Engineers,Secondary,Design or analyze operational solutions for pr...
5,17-2031.00,Bioengineers and Biomedical Engineers,NaN,"Apply knowledge of engineering, biology, chemi..."
6,17-2041.00,Chemical Engineers,Primary,Design chemical plant equipment and devise pro...
7,17-2112.02,Validation Engineers,NaN,Design or plan protocols for equipment or proc...
8,17-2112.03,Manufacturing Engineers,Primary,"Design, integrate, or improve manufacturing sy..."
9,17-2141.00,Mechanical Engineers,Primary,Perform engineering duties in planning and des...
10,17-2141.02,Automotive Engineers,NaN,Develop new or improved designs for vehicle st...
11,17-2199.05,Mechatronics Engineers,Primary,"Research, design, develop, or test automation,..."
12,17-2199.08,Robotics Engineers,Primary,"Research, design, develop, or test robotic app..."
13,17-3024.01,Robotics Technicians,NaN,"Build, install, test, or maintain robotic equi..."
14,17-3026.00,Industrial Engineering Technologists and Techn...,Primary,Apply engineering theory and principles to pro...
15,17-3027.00,Mechanical Engineering Technologists and Techn...,Primary,Apply theory and principles of mechanical engi...
16,19-1021.00,Biochemists and Biophysicists,NaN,Study the chemical composition or physical pri...
17,19-1022.00,Microbiologists,NaN,"Investigate the growth, structure, development..."
18,19-2031.00,Chemists,NaN,Conduct qualitative and quantitative chemical ...

In [12]:
# Unir DataFrames
# Aquí debes definir la columna clave común en ambos DF, por ejemplo 'dwa_id'
df_merged = pd.merge(df_final, df_excel, on="title", how="left")

print(f"DataFrame final tiene {df_merged.shape[0]} filas y {df_merged.shape[1]} columnas.")

DataFrame final tiene 560 filas y 10 columnas.

In [13]:
display(df_merged)

,onetsoc_code,title,task_id,task,dwa_id,dwa_title,archivo_origen,o.net.soc.code,icbe,description
0,17-2141.02,Automotive Engineers,16421,"Read current literature, attend meetings or co...",4.A.2.b.3.I01.D20,Update technical knowledge.,Automotive_Engineers.csv,17-2141.02,NaN,Develop new or improved designs for vehicle st...
1,17-2141.02,Automotive Engineers,16422,Establish production or quality control standa...,4.A.2.b.2.I07.D06,Determine operational criteria or specifications.,Automotive_Engineers.csv,17-2141.02,NaN,Develop new or improved designs for vehicle st...
2,17-2141.02,Automotive Engineers,16423,Prepare or present technical or project status...,4.A.3.b.6.I15.D04,Prepare operational reports.,Automotive_Engineers.csv,17-2141.02,NaN,Develop new or improved designs for vehicle st...
3,17-2141.02,Automotive Engineers,16424,Develop or implement operating methods or proc...,4.A.2.b.1.I09.D06,Implement design or process improvements.,Automotive_Engineers.csv,17-2141.02,NaN,Develop new or improved designs for vehicle st...
4,17-2141.02,Automotive Engineers,16424,Develop or implement operating methods or proc...,4.A.2.b.4.I03.D14,Develop technical methods or processes.,Automotive_Engineers.csv,17-2141.02,NaN,Develop new or improved designs for vehicle st...
...,...,...,...,...,...,...,...,...,...,...
555,11-3051.01,Quality Control Systems Managers,15428,Analyze quality control test results and provi...,4.A.2.a.4.I07.D12,Analyze data to inform operational decisions o...,Quality_Control_Systems_Managers.csv,11-3051.01,Secondary,"Plan, direct, or coordinate quality assurance ..."
556,11-3051.01,Quality Control Systems Managers,15428,Analyze quality control test results and provi...,4.A.4.a.2.I03.D14,Confer with organizational members to accompli...,Quality_Control_Systems_Managers.csv,11-3051.01,Secondary,"Plan, direct, or coordinate quality assurance ..."
557,11-3051.01,Quality Control Systems Managers,15429,"Oversee workers including supervisors, inspect...",4.A.4.b.4.I01.D13,Supervise employees.,Quality_Control_Systems_Managers.csv,11-3051.01,Secondary,"Plan, direct, or coordinate quality assurance ..."
558,11-3051.01,Quality Control Systems Managers,15430,Monitor performance of quality control systems...,4.A.1.a.2.I02.D05,Monitor organizational procedures to ensure pr...,Quality_Control_Systems_Managers.csv,11-3051.01,Secondary,"Plan, direct, or coordinate quality assurance ..."
559,11-3051.01,Quality Control Systems Managers,15431,Direct product testing activities throughout p...,4.A.4.b.4.I08.D03,Manage control system activities in organizati...,Quality_Control_Systems_Managers.csv,11-3051.01,Secondary,"Plan, direct, or coordinate quality assurance ..."

### Ocuppations

In [14]:
from pprint import pprint
occupations = df_excel['title'].tolist()
pprint(occupations)

['Industrial Production Managers',
 'Quality Control Systems Managers',
 'Supply Chain Managers',
 'Human Resources Managers',
 'Logistics Engineers',
 'Bioengineers and Biomedical Engineers',
 'Chemical Engineers',
 'Validation Engineers',
 'Manufacturing Engineers',
 'Mechanical Engineers',
 'Automotive Engineers',
 'Mechatronics Engineers',
 'Robotics Engineers',
 'Robotics Technicians',
 'Industrial Engineering Technologists and Technicians',
 'Mechanical Engineering Technologists and Technicians',
 'Biochemists and Biophysicists',
 'Microbiologists',
 'Chemists']

In [15]:
print(len(occupations))

19

### DWAs

In [16]:
conteo = pd.DataFrame(df_final["dwa_title"].value_counts())

display(conteo)

                                                    count
dwa_title
Design industrial processing systems.                  11
Recommend technical design or process changes t...     11
Program robotic equipment.                             11
Design electromechanical equipment or systems.         11
Estimate operational costs.                            10
...                                                   ...
Monitor performance of organizational members o...      1
Manage inventories of products or organizationa...      1
Develop organizational goals or objectives.             1
Determine operational criteria or specifications.       1
Communicate organizational information to custo...      1

[221 rows x 1 columns]

In [17]:
num_compartidos = conteo[conteo['count'] > 1]
display(num_compartidos)

                                                    count
dwa_title
Design industrial processing systems.                  11
Recommend technical design or process changes t...     11
Program robotic equipment.                             11
Design electromechanical equipment or systems.         11
Estimate operational costs.                            10
...                                                   ...
Direct operational or production activities.            2
Monitor processes for compliance with standards.        2
Research industrial processes or operations.            2
Direct organizational operations, projects, or ...      2
Negotiate sales or lease agreements for product...      2

[126 rows x 1 columns]

In [18]:
221-126

95

Hay 95 dwa que se comparten entre las 19 occupations.

## DWAs save

In [26]:
dwa = pd.DataFrame(df_final['dwa_title'])
display(dwa)

                                             dwa_title
0                          Update technical knowledge.
1    Determine operational criteria or specifications.
2                         Prepare operational reports.
3            Implement design or process improvements.
4              Develop technical methods or processes.
..                                                 ...
555  Analyze data to inform operational decisions o...
556  Confer with organizational members to accompli...
557                               Supervise employees.
558  Monitor organizational procedures to ensure pr...
559  Manage control system activities in organizati...

[560 rows x 1 columns]

In [27]:
print(len(dwa['dwa_title'].tolist()))

560

In [22]:
import re, unicodedata

# --- Regex precompiles ---
RE_ZERO_WIDTH   = re.compile(r'[\u200B-\u200F\u202A-\u202E\u2060\uFEFF]')
RE_SPACES       = re.compile(r'\s+')
RE_TRAILING_DOT = re.compile(r'[.\s]+$')

# Clase de comillas (ASCII + tipográficas + angulares)
QUOTE_UTF8_CHARS = '"\'`“”„‟‘’‚‛«»‹›'
RE_EDGE_QUOTES   = re.compile(rf'^[{re.escape(QUOTE_UTF8_CHARS)}\s]+|[{re.escape(QUOTE_UTF8_CHARS)}\s]+$')

# Mojibake -> UTF-8/ASCII
MOJIBAKE_MAP = {
    "â¢": "•",
    "â": "—",
    "â": "–",
    "â¦": "…",
    "â": "'",
    "â": "'",
    "â": '"',
    "â": '"',
    "â": "",
}

# Enumeraciones iniciales (NO metas comillas aquí)
LEADING_ENUM_PATTERNS = [
    re.compile(r'^\s*\d+\s*\t+\s*'),               # "12\t..."
    re.compile(r'^\s*\d+\s*[\.\)]\s*'),            # "1." / "2)"
    re.compile(r'^\s*[\(\[]\s*\d+\s*[\)\]]\s*'),   # "(1)" / "[2]"
    re.compile(r'^\s*\d+\s*[-–—]\s+'),             # "1 - " / "1 – " / "1 — "
    re.compile(r'^\s*[A-Za-z]\s*[\.\)]\s+'),       # "a) " / "B. "
    re.compile(r'^\s*[ivxlcdmIVXLCDM]+\s*[\.\)]\s+'),  # "IV. " / "i) "
    re.compile(r'^\s*[•\-\*\u2219·–—]\s*\t+\s*'),  # bullets con tab
    re.compile(r'^\s*[•\-\*\u2219·–—]\s+'),        # bullets con espacio
]

def _strip_edge_quotes_loop(s: str) -> str:
    """Recorta comillas/espacios en bordes de forma repetida (izq./der.)."""
    while True:
        new_s = RE_EDGE_QUOTES.sub('', s).strip()
        if new_s == s:
            return s
        s = new_s

def clean_skill(text: str) -> str:
    """
    Devuelve la skill limpia en minúsculas:
      - quita enumeraciones iniciales,
      - recorta comillas de borde (ASCII/UTF-8),
      - corrige mojibake, elimina zero-width/bidi/BOM,
      - quita punto(s) finales,
      - conserva paréntesis internos.
    """
    if text is None:
        return ""
    s = unicodedata.normalize("NFKC", str(text))

    # Mojibake -> UTF8/ASCII
    for bad, good in MOJIBAKE_MAP.items():
        if bad in s:
            s = s.replace(bad, good)

    # Invisibles
    s = RE_ZERO_WIDTH.sub("", s)

    # Enumeraciones al inicio (pelar en capas)
    prev = None
    while s != prev:
        prev = s
        for pat in LEADING_ENUM_PATTERNS:
            s = pat.sub("", s, count=1)

    # Normaliza espacios
    s = RE_SPACES.sub(" ", s).strip()

    # 1ª pasada: recortar comillas de borde
    s = _strip_edge_quotes_loop(s)

    # Quitar punto(s) finales
    s = RE_TRAILING_DOT.sub("", s).strip()

    # 2ª pasada: recortar comillas de borde (para casos como ”.)
    s = _strip_edge_quotes_loop(s)

    # Minúsculas
    return s.lower().strip()

def _t(inp, expected):
    got = clean_skill(inp)
    assert got == expected, f"\nINPUT : {repr(inp)}\nGOT   : {repr(got)}\nEXPECT: {repr(expected)}"

# Comillas (ASCII, tipográficas, angulares) + punto final
_t('"Python Programming"', 'python programming')
_t('“Python Programming”.', 'python programming')
_t("‘Skill’", 'skill')
_t("«Skill»", 'skill')
_t("‹Skill›", 'skill')
_t("`Skill`", 'skill')
_t("' Skill '", 'skill')

# Punto final en skills largas
_t("Long descriptive skill.", "long descriptive skill")
_t("C++.", "c++")

# Mayúsculas/minúsculas
_t("JAVA", "java")
_t("Title Case Mixed", "title case mixed")

# Enumeraciones (número + tab / . / ) / (1) / [2] / 1 - / letra) / romanos / bullets
_t("12\tSystems Design", "systems design")
_t("1.\tSkill", "skill")
_t("(1)\tSkill", "skill")
_t("[2] Skill", "skill")
_t("1 - Skill", "skill")
_t("a)\tSkill", "skill")
_t("IV.\tSkill", "skill")
_t("•\tLeadership", "leadership")
_t("-\tProject Management", "project management")
_t("—\tSystems", "systems")
_t("–\tSystems", "systems")
_t("• bullet style skill", "bullet style skill")
_t("·\tAnother Skill", "another skill")

# Mojibake en medio del texto + zero-width
_t("4Aâs Marketing", "4a's marketing")
_t("Hâow to Design", "how to design")

# Paréntesis preservados
_t("Design (CAD)", "design (cad)")
_t("A/B Testing (advanced)", "a/b testing (advanced)")

In [28]:
temp=dwa['dwa_title'].apply(clean_skill)


display(temp)

0                             update technical knowledge
1       determine operational criteria or specifications
2                            prepare operational reports
3               implement design or process improvements
4                 develop technical methods or processes
                             ...
555    analyze data to inform operational decisions o...
556    confer with organizational members to accompli...
557                                  supervise employees
558    monitor organizational procedures to ensure pr...
559    manage control system activities in organizations
Name: dwa_title, Length: 560, dtype: object

In [29]:
conteo = pd.DataFrame(temp.value_counts())

display(conteo)

                                                    count
dwa_title
design industrial processing systems                   11
recommend technical design or process changes t...     11
program robotic equipment                              11
design electromechanical equipment or systems          11
estimate operational costs                             10
...                                                   ...
monitor performance of organizational members o...      1
manage inventories of products or organizationa...      1
develop organizational goals or objectives              1
determine operational criteria or specifications        1
communicate organizational information to custo...      1

[221 rows x 1 columns]

In [30]:
for i in temp:
    print(i)

update technical knowledge
determine operational criteria or specifications
prepare operational reports
implement design or process improvements
develop technical methods or processes
prepare technical reports for internal use
maintain operational records or records systems
research advanced engineering designs or applications
coordinate activities with suppliers, contractors, clients, or other departments
provide technical guidance to other personnel
conduct quantitative failure analyses of operational data
determine design criteria or specifications
estimate operational costs
determine design criteria or specifications
devise research or testing protocols
evaluate technical data to determine effect on designs or plans
calibrate scientific or technical equipment
create models of engineering designs or methods
design electromechanical equipment or systems
evaluate characteristics of equipment or systems
design electromechanical equipment or systems
test performance of electrical, electronic, mechanical, or integrated systems or equipment
direct design or development activities
design control systems for mechanical or other equipment
design energy-efficient vehicles or vehicle components
design energy-efficient vehicles or vehicle components
design energy-efficient vehicles or vehicle components
determine design criteria or specifications
research advanced engineering designs or applications
research design or application of green technologies
determine operational methods
create graphical representations of industrial production systems
confer with technical personnel to prepare designs or operational plans
determine causes of operational problems or failures
design industrial equipment
install production equipment or systems
estimate operational costs
estimate technical or resource requirements for development or production projects
estimate time requirements for development or production projects
assess product or process usefulness
analyze operational data to evaluate operations, processes or products
resolve operational performance problems
prepare procedural documents
purchase materials, equipment, or other resources
evaluate designs or specifications to ensure quality
determine causes of operational problems or failures
prepare operational reports
provide technical guidance to other personnel
update technical knowledge
supervise production or support personnel
train personnel on proper operational procedures
analyze costs and benefits of proposed designs or projects
design industrial processing systems
investigate the environmental impact of projects
develop operational methods or processes that use green materials or emphasize sustainability
implement design or process improvements
develop technical methods or processes
design industrial processing systems
determine causes of operational problems or failures
recommend technical design or process changes to improve efficiency, quality, or performance
devise research or testing protocols
train personnel on proper operational procedures
prepare procedural documents
recommend technical design or process changes to improve efficiency, quality, or performance
confer with technical personnel to prepare designs or operational plans
communicate technical information to suppliers, contractors, or regulatory agencies
communicate technical information to suppliers, contractors, or regulatory agencies
confer with technical personnel to prepare designs or operational plans
confer with technical personnel to prepare designs or operational plans
design medical devices or appliances
research engineering aspects of biological or chemical processes
design medical devices or appliances
devise research or testing protocols
develop operational methods or processes that use green materials or emphasize sustainability
develop technical methods or processes
create models of engineering designs or methods
research engineering aspects of biological or chemical processes
maintain operational records or records systems
supervise engineering or other technical personnel
estimate operational costs
estimate time requirements for development or production projects
prepare detailed work plans
prepare technical reports for internal use
prepare contracts, disclosures, or applications
update technical knowledge
recommend technical design or process changes to improve efficiency, quality, or performance
research engineering aspects of biological or chemical processes
evaluate characteristics of equipment or systems
advise customers on the use of products or services
research engineering aspects of biological or chemical processes
create models of engineering designs or methods
research engineering aspects of biological or chemical processes
develop software or computer applications
analyze operational data to evaluate operations, processes or products
supervise engineering or other technical personnel
design electromechanical equipment or systems
advise customers on the use of products or services
evaluate designs or specifications to ensure quality
document technical design details
prepare operational reports
program robotic equipment
maintain operational records or records systems
interpret design or operational test results
program robotic equipment
investigate system, equipment, or product failures
calibrate scientific or technical equipment
install production equipment or systems
operate industrial equipment
program robotic equipment
design industrial equipment
research advanced engineering designs or applications
program robotic equipment
research advanced engineering designs or applications
design industrial processing systems
develop software or computer applications
design electromechanical equipment or systems
develop operational methods or processes that use green materials or emphasize sustainability
design industrial processing systems
test performance of electrical, electronic, mechanical, or integrated systems or equipment
design electromechanical equipment or systems
program robotic equipment
evaluate characteristics of equipment or systems
document design or operational test results
train personnel on proper operational procedures
provide technical guidance to other personnel
recommend technical design or process changes to improve efficiency, quality, or performance
supervise engineering or other technical personnel
create graphical representations of mechanical equipment
maintain operational records or records systems
recommend technical design or process changes to improve efficiency, quality, or performance
test performance of electrical, electronic, mechanical, or integrated systems or equipment
implement design or process improvements
research engineering applications of emerging technologies
select tools, equipment, or technologies for use in operations or projects
design electromechanical equipment or systems
design industrial processing systems
design control systems for mechanical or other equipment
develop software or computer applications
design electromechanical equipment or systems
develop technical methods or processes
design electromechanical equipment or systems
design electromechanical equipment or systems
design electromechanical equipment or systems
design environmental control systems
design control systems for mechanical or other equipment
monitor the productivity or efficiency of industrial operations
calibrate scientific or technical equipment
estimate technical or resource requirements for development or production projects
select project materials
analyze design or requirements information for mechanical equipment or systems
create physical models or prototypes
estimate operational costs
review technical documents to plan work
confer with other personnel to resolve design or operational problems
confer with technical personnel to prepare designs or operational plans
analyze design or requirements information for mechanical equipment or systems
recommend technical design or process changes to improve efficiency, quality, or performance
direct installation activities
direct equipment maintenance or repair activities
test performance of electrical, electronic, mechanical, or integrated systems or equipment
recommend technical design or process changes to improve efficiency, quality, or performance
direct industrial production activities
determine operational methods
direct equipment maintenance or repair activities
coordinate safety or regulatory compliance activities
document technical design details
identify new applications for existing technologies
design electronic or computer equipment or instrumentation
estimate operational costs
design industrial processing systems
direct installation activities
evaluate plans or specifications to determine technological or environmental implications
advise others regarding green practices or environmental concerns
select tools, equipment, or technologies for use in operations or projects
install production equipment or systems
evaluate characteristics of equipment or systems
design industrial processing systems
design industrial equipment
investigate system, equipment, or product failures
recommend technical design or process changes to improve efficiency, quality, or performance
test performance of electrical, electronic, mechanical, or integrated systems or equipment
create models of engineering designs or methods
implement design or process improvements
estimate operational costs
prepare proposal documents
supervise production or support personnel
perform marketing activities
advise customers on the use of products or services
research industrial processes or operations
monitor processes for compliance with standards
test products for functionality or quality
inspect operational processes
monitor activities affecting environmental quality
estimate operational costs
analyze costs and benefits of proposed designs or projects
create physical models or prototypes
develop technical methods or processes
calibrate scientific or technical equipment
analyze costs and benefits of proposed designs or projects
purchase materials, equipment, or other resources
prepare drawings or diagrams of products or services
explain engineering drawings, specifications, or other technical information
design structures or facilities
design industrial processing systems
implement design or process improvements
develop technical methods or processes
develop technical methods or processes
design industrial processing systems
design industrial equipment
monitor the productivity or efficiency of industrial operations
calibrate scientific or technical equipment
direct quality control activities
direct industrial production activities
create graphical representations of industrial production systems
prepare operational reports
train personnel on proper operational procedures
recommend technical design or process changes to improve efficiency, quality, or performance
select project materials
determine operational methods
select project materials
operate industrial equipment
research human performance or health factors related to engineering or design activities
prepare detailed work plans
monitor processes for compliance with standards
assess product or process usefulness
create graphical representations of mechanical equipment
prepare contracts, disclosures, or applications
create graphical representations of mechanical equipment
review technical documents to plan work
review technical documents to plan work
test performance of electrical, electronic, mechanical, or integrated systems or equipment
analyze test or validation data
evaluate designs or specifications to ensure quality
estimate technical or resource requirements for development or production projects
document design or operational test results
monitor the productivity or efficiency of industrial operations
estimate operational costs
test products for functionality or quality
analyze green technology design requirements
estimate operational costs
assemble equipment or components
test products for functionality or quality
test performance of electrical, electronic, mechanical, or integrated systems or equipment
design industrial equipment
assist engineers or scientists with research
conduct quantitative failure analyses of operational data
document design or operational test results
recommend technical design or process changes to improve efficiency, quality, or performance
analyze costs and benefits of proposed designs or projects
design industrial equipment
design industrial equipment
design industrial equipment
assemble mechanical components or machine parts
fabricate devices or components
collaborate with others to develop or refine designs
explain engineering drawings, specifications, or other technical information
schedule operational activities
create graphical representations of industrial production systems
create graphical representations of mechanical equipment
document technical design details
provide technical guidance to other personnel
test characteristics of materials or structures
test performance of electrical, electronic, mechanical, or integrated systems or equipment
train personnel on proper operational procedures
program robotic equipment
maintain operational records or records systems
fabricate products or components using machine tools
prepare procedural documents
document design or operational test results
create graphical representations of industrial production systems
inspect facilities or sites to determine if they meet specifications or standards
program robotic equipment
program robotic equipment
assemble equipment or components
design electromechanical equipment or systems
assemble equipment or components
determine causes of operational problems or failures
program robotic equipment
test performance of electrical, electronic, mechanical, or integrated systems or equipment
maintain electromechanical equipment
program robotic equipment
maintain electromechanical equipment
install production equipment or systems
assemble equipment or components
evaluate characteristics of equipment or systems
calibrate scientific or technical equipment
program robotic equipment
operate industrial equipment
assemble equipment or components
maintain electromechanical equipment
repair electronic equipment
maintain inventories of materials, equipment, or products
implement transportation changes to reduce environmental impact
document organizational or operational procedures
negotiate contracts for transportation, distribution, or logistics services
coordinate with external parties to exchange information
document organizational or operational procedures
implement organizational process or policy changes
develop procedures to evaluate organizational activities
implement organizational process or policy changes
develop operating strategies, plans, or procedures
confer with organizational members to accomplish work activities
develop organizational goals or objectives
develop procedures to evaluate organizational activities
analyze data to inform operational decisions or activities
analyze data to assess operational or project effectiveness
manage operations, research, or logistics projects
develop operating strategies, plans, or procedures
implement organizational process or policy changes
develop organizational methods or procedures
evaluate environmental impact of operational or development activities
implement organizational process or policy changes
develop sustainable organizational policies or practices
implement organizational process or policy changes
develop sustainable organizational policies or practices
evaluate quality of materials or products
develop sustainable organizational policies or practices
identify opportunities for green initiatives
evaluate environmental impact of operational or development activities
identify opportunities for green initiatives
implement organizational process or policy changes
estimate labor requirements
estimate cost or material requirements
manage inventories of products or organizational resources
manage operations, research, or logistics projects
monitor performance of organizational members or partners
monitor external affairs or events affecting business operations
confer with organizational members to accomplish work activities
estimate cost or material requirements
evaluate potential of products, technologies, or resources
estimate labor requirements
prepare operational budgets
perform human resources activities
administer standardized physical or psychological tests
manage human resources activities
maintain knowledge of current developments in area of expertise
manage human resources activities
coordinate special events or programs
advise others on career or personal development
negotiate sales or lease agreements for products or services
manage human resources activities
administer compensation or benefits programs
interview employees, customers, or others to collect information
hire personnel
recruit personnel
manage human resources activities
communicate organizational policies and procedures
manage human resources activities
hire personnel
recommend organizational process or policy changes
advise others on legal or regulatory compliance matters
analyze data to inform operational decisions or activities
administer compensation or benefits programs
conduct employee training programs
liaise between departments or other groups to improve function or communication
supervise employees
manage human resources activities
manage human resources activities
compile operational data
maintain personnel records
analyze data to inform personnel decisions
manage human resources activities
interview employees, customers, or others to collect information
investigate industrial or transportation accidents
prepare reports related to compliance matters
represent the organization in external relations
negotiate labor disputes
conduct environmental audits
design industrial processing systems
direct operational or production activities
respond to emergencies to provide assistance
maintain regulatory or compliance documentation
monitor external affairs or events affecting business operations
implement design or process improvements
prepare operational reports
supervise employees
direct sales, marketing, or customer service activities
direct organizational operations, projects, or services
approve expenditures
prepare operational budgets
analyze data to inform operational decisions or activities
monitor organizational procedures to ensure proper functioning
confer with organizational members to accomplish work activities
evaluate employee performance
conduct employee training programs
hire personnel
manage control system activities in organizations
maintain personnel records
prepare operational progress or status reports
evaluate quality of materials or products
develop operating strategies, plans, or procedures
analyze data to inform operational decisions or activities
implement organizational process or policy changes
develop organizational methods or procedures
develop specifications for new products or processes
confer with organizational members to accomplish work activities
direct facility maintenance or repair activities
recommend organizational process or policy changes
maintain knowledge of current developments in area of expertise
negotiate sales or lease agreements for products or services
analyze chemical compounds or substances
develop new or advanced products or production methods
collaborate on research activities with scientists or technical specialists
supervise scientific or technical personnel
analyze chemical compounds or substances
establish standards for products, processes, or procedures
prepare scientific or technical reports or presentations
research methods to improve food products
prepare compounds or solutions for products or testing
maintain laboratory or technical equipment

In [31]:
dwa2 = dwa.copy()
dwa2['dwa_title'] = temp

display(dwa2)

                                             dwa_title
0                           update technical knowledge
1     determine operational criteria or specifications
2                          prepare operational reports
3             implement design or process improvements
4               develop technical methods or processes
..                                                 ...
555  analyze data to inform operational decisions o...
556  confer with organizational members to accompli...
557                                supervise employees
558  monitor organizational procedures to ensure pr...
559  manage control system activities in organizations

[560 rows x 1 columns]

In [39]:
import csv

formato =[".csv", ".tsv"] 

OUT_DIR2 = Path(path+"/results")
OUT_DIR2.mkdir(parents=True, exist_ok=True)

for i in formato:
    dwa2.to_csv(f"{OUT_DIR2}/dwas{i}", index=False, encoding="utf-8",
                        quoting=csv.QUOTE_MINIMAL, quotechar='"', escapechar='\\')

## Filtrado 8 saved

In [21]:
# Eliminar columnas no deseadas
filtrado8 = df_final[["title", "dwa_title",]]

display(filtrado8)

,title,dwa_title
0,Automotive Engineers,Update technical knowledge.
1,Automotive Engineers,Determine operational criteria or specifications.
2,Automotive Engineers,Prepare operational reports.
3,Automotive Engineers,Implement design or process improvements.
4,Automotive Engineers,Develop technical methods or processes.
...,...,...
555,Quality Control Systems Managers,Analyze data to inform operational decisions o...
556,Quality Control Systems Managers,Confer with organizational members to accompli...
557,Quality Control Systems Managers,Supervise employees.
558,Quality Control Systems Managers,Monitor organizational procedures to ensure pr...
559,Quality Control Systems Managers,Manage control system activities in organizati...

In [40]:
for i in formato:
    filtrado8.to_csv(f"{OUT_DIR2}/filtrado8_results{i}", index=False, encoding="utf-8",
                        quoting=csv.QUOTE_MINIMAL, quotechar='"', escapechar='\\')