# Coursera
Creacion del conjunto de datos a partir del json que surge del web scrapping. Paso 4: recomendar cursos a partir de skills de coursera.

In [21]:
import pandas as pd

# Cargar directamente desde archivo JSON
df_final = pd.read_json("courses.json")

display(df_final.head())

,url,name,topics,skills,description,language,outcomes
0,https://www.coursera.org/learn/ibm-cyber-threa...,Cyber Threat Intelligence | Coursera,"[Information Technology, Security]","[Application Security, threat intelligence, ne...",This course gives you the background needed to...,English,[]
1,https://www.coursera.org/learn/-network-security,Network Security | Coursera,"[Information Technology, Security]","[Cyberattacks, Network Security, Threat]",Welcome to course 4 of 5 of this Specializatio...,English,[]
2,https://www.coursera.org/learn/-security-princ...,Security Principles | Coursera,"[Information Technology, Security]","[Risk, Information Assurance, security, govern...",Welcome to course 1 of 5 of this Specializatio...,English,[]
3,https://www.coursera.org/learn/10k-women-1,"Grow Your Business with Goldman Sachs 10,000 W...","[Business, Entrepreneurship]","[Opportunity Identification, Strategic Thinkin...",This free online course is one of 10 courses a...,English,[Develop your community and discuss the value ...
4,https://www.coursera.org/learn/10k-women-10,"Fundamentals of Negotiation, with Goldman Sach...","[Business, Entrepreneurship]","[Emotional Intelligence, Customer Relationship...",This free online course is one of 10 courses a...,English,"[Review how to establish rapport, trust, and r..."

## Arreglo de skills

In [22]:
df_exploded = df_final.explode("skills")
display(df_exploded)

,url,name,topics,skills,description,language,outcomes
0,https://www.coursera.org/learn/ibm-cyber-threa...,Cyber Threat Intelligence | Coursera,"[Information Technology, Security]",Application Security,This course gives you the background needed to...,English,[]
0,https://www.coursera.org/learn/ibm-cyber-threa...,Cyber Threat Intelligence | Coursera,"[Information Technology, Security]",threat intelligence,This course gives you the background needed to...,English,[]
0,https://www.coursera.org/learn/ibm-cyber-threa...,Cyber Threat Intelligence | Coursera,"[Information Technology, Security]",network defensive tactics,This course gives you the background needed to...,English,[]
0,https://www.coursera.org/learn/ibm-cyber-threa...,Cyber Threat Intelligence | Coursera,"[Information Technology, Security]",security analyst,This course gives you the background needed to...,English,[]
0,https://www.coursera.org/learn/ibm-cyber-threa...,Cyber Threat Intelligence | Coursera,"[Information Technology, Security]",Cybersecurity,This course gives you the background needed to...,English,[]
...,...,...,...,...,...,...,...
5263,https://www.coursera.org/learn/zn-and-ni-based...,Zn and Ni Based Batteries | Coursera,"[Physical Science and Engineering, Electrical ...",battery charging,Zn and Ni based Batteries: This course focuses...,English,"[ Participants will learn active materials, ch..."
5264,https://www.coursera.org/learn/zos-rexx-progra...,IBM z/OS Rexx Programming | Coursera,"[Computer Science, Software Development]",Computer Programming,This course is designed to teach you the basic...,English,"[Write programs using REXX, Create user-define..."
5264,https://www.coursera.org/learn/zos-rexx-progra...,IBM z/OS Rexx Programming | Coursera,"[Computer Science, Software Development]",Mainframe Coding,This course is designed to teach you the basic...,English,"[Write programs using REXX, Create user-define..."
5264,https://www.coursera.org/learn/zos-rexx-progra...,IBM z/OS Rexx Programming | Coursera,"[Computer Science, Software Development]",REXX,This course is designed to teach you the basic...,English,"[Write programs using REXX, Create user-define..."
5265,https://www.coursera.org/learn/zos-system-serv...,z/OS System Services Structure | Coursera,"[Information Technology, Data Management]",NaN,This course presents the structure and control...,English,[]

In [23]:
# Eliminar filas donde 'skills' esté vacío o NaN
df_exploded = df_exploded[df_exploded["skills"].notna() & (df_exploded["skills"] != "")]

In [24]:
import re, unicodedata

# --- Regex precompiles ---
RE_ZERO_WIDTH   = re.compile(r'[\u200B-\u200F\u202A-\u202E\u2060\uFEFF]')
RE_SPACES       = re.compile(r'\s+')
RE_TRAILING_DOT = re.compile(r'[.\s]+$')

# Clase de comillas (ASCII + tipográficas + angulares)
QUOTE_UTF8_CHARS = '"\'`“”„‟‘’‚‛«»‹›'
RE_EDGE_QUOTES   = re.compile(rf'^[{re.escape(QUOTE_UTF8_CHARS)}\s]+|[{re.escape(QUOTE_UTF8_CHARS)}\s]+$')

# Mojibake -> UTF-8/ASCII
MOJIBAKE_MAP = {
    "â¢": "•",
    "â": "—",
    "â": "–",
    "â¦": "…",
    "â": "'",
    "â": "'",
    "â": '"',
    "â": '"',
    "â": "",
}

# Enumeraciones iniciales (NO metas comillas aquí)
LEADING_ENUM_PATTERNS = [
    re.compile(r'^\s*\d+\s*\t+\s*'),               # "12\t..."
    re.compile(r'^\s*\d+\s*[\.\)]\s*'),            # "1." / "2)"
    re.compile(r'^\s*[\(\[]\s*\d+\s*[\)\]]\s*'),   # "(1)" / "[2]"
    re.compile(r'^\s*\d+\s*[-–—]\s+'),             # "1 - " / "1 – " / "1 — "
    re.compile(r'^\s*[A-Za-z]\s*[\.\)]\s+'),       # "a) " / "B. "
    re.compile(r'^\s*[ivxlcdmIVXLCDM]+\s*[\.\)]\s+'),  # "IV. " / "i) "
    re.compile(r'^\s*[•\-\*\u2219·–—]\s*\t+\s*'),  # bullets con tab
    re.compile(r'^\s*[•\-\*\u2219·–—]\s+'),        # bullets con espacio
]

def _strip_edge_quotes_loop(s: str) -> str:
    """Recorta comillas/espacios en bordes de forma repetida (izq./der.)."""
    while True:
        new_s = RE_EDGE_QUOTES.sub('', s).strip()
        if new_s == s:
            return s
        s = new_s

def clean_skill(text: str) -> str:
    """
    Devuelve la skill limpia en minúsculas:
      - quita enumeraciones iniciales,
      - recorta comillas de borde (ASCII/UTF-8),
      - corrige mojibake, elimina zero-width/bidi/BOM,
      - quita punto(s) finales,
      - conserva paréntesis internos.
    """
    if text is None:
        return ""
    s = unicodedata.normalize("NFKC", str(text))

    # Mojibake -> UTF8/ASCII
    for bad, good in MOJIBAKE_MAP.items():
        if bad in s:
            s = s.replace(bad, good)

    # Invisibles
    s = RE_ZERO_WIDTH.sub("", s)

    # Enumeraciones al inicio (pelar en capas)
    prev = None
    while s != prev:
        prev = s
        for pat in LEADING_ENUM_PATTERNS:
            s = pat.sub("", s, count=1)

    # Normaliza espacios
    s = RE_SPACES.sub(" ", s).strip()

    # 1ª pasada: recortar comillas de borde
    s = _strip_edge_quotes_loop(s)

    # Quitar punto(s) finales
    s = RE_TRAILING_DOT.sub("", s).strip()

    # 2ª pasada: recortar comillas de borde (para casos como ”.)
    s = _strip_edge_quotes_loop(s)

    # Minúsculas
    return s.lower().strip()

def _t(inp, expected):
    got = clean_skill(inp)
    assert got == expected, f"\nINPUT : {repr(inp)}\nGOT   : {repr(got)}\nEXPECT: {repr(expected)}"

# Comillas (ASCII, tipográficas, angulares) + punto final
_t('"Python Programming"', 'python programming')
_t('“Python Programming”.', 'python programming')
_t("‘Skill’", 'skill')
_t("«Skill»", 'skill')
_t("‹Skill›", 'skill')
_t("`Skill`", 'skill')
_t("' Skill '", 'skill')

# Punto final en skills largas
_t("Long descriptive skill.", "long descriptive skill")
_t("C++.", "c++")

# Mayúsculas/minúsculas
_t("JAVA", "java")
_t("Title Case Mixed", "title case mixed")

# Enumeraciones (número + tab / . / ) / (1) / [2] / 1 - / letra) / romanos / bullets
_t("12\tSystems Design", "systems design")
_t("1.\tSkill", "skill")
_t("(1)\tSkill", "skill")
_t("[2] Skill", "skill")
_t("1 - Skill", "skill")
_t("a)\tSkill", "skill")
_t("IV.\tSkill", "skill")
_t("•\tLeadership", "leadership")
_t("-\tProject Management", "project management")
_t("—\tSystems", "systems")
_t("–\tSystems", "systems")
_t("• bullet style skill", "bullet style skill")
_t("·\tAnother Skill", "another skill")

# Mojibake en medio del texto + zero-width
_t("4Aâs Marketing", "4a's marketing")
_t("Hâow to Design", "how to design")

# Paréntesis preservados
_t("Design (CAD)", "design (cad)")
_t("A/B Testing (advanced)", "a/b testing (advanced)")

In [25]:
temp=df_exploded['skills'].apply(clean_skill)


display(temp)

0            application security
0             threat intelligence
0       network defensive tactics
0                security analyst
0                   cybersecurity
                  ...
5263                battery types
5263             battery charging
5264         computer programming
5264             mainframe coding
5264                         rexx
Name: skills, Length: 12674, dtype: object

In [26]:
conteo = pd.DataFrame(temp.value_counts())

display(conteo)

                                                    count
skills
data analysis                                         170
python programming                                    160
machine learning                                      117
communication                                         106
data visualization (dataviz)                           83
...                                                   ...
triboelectric                                           1
designing and redesigning energy systems to put...      1
recognizing energy injustice                            1
applying concepts and tools to advance energy j...      1
rexx                                                    1

[5304 rows x 1 columns]

In [27]:
for i in temp:
    print(i)

application security
threat intelligence
network defensive tactics
security analyst
cybersecurity
cyberattacks
network security
threat
risk
information assurance
security
governance
opportunity identification
strategic thinking
business analytics
entrepreneurship
emotional intelligence
customer relationship management (crm)
communication
bargaining
negotiation
income statement analysis
balance sheet
financial terminology
financial statement use and analysis
financial ratio analysis
leadership
strategic planning
vision statement development
business culture analysis
customer value proposition (cvp) development
strategic pricing
competitive advantage analysis
competitive analysis
financial management
strategic planning
cash flow cycle analysis
cash flow forecast analysis
market research
marketing strategy development
value proposition analysis
brand identity and management
process management
operations management
business modelling
communication
leadership
performance management
business culture development
financial management
funding requirement analysis
funding applications
strategic financial planning
analytics
marketing design
digital marketing
market research
concept testing
product development
influencing business culture
evaluation
social corporate responsibility
healthcare
leadership
risk assessment
prevention
manufacturing process management
computer-aided design (cad)
computer-aided manufacturing
autodesk fusion 360
mechanical engineering
virtual reality
camera+
video production
360-degree video
opengl++
vr
sensors
android studio
textures
materials
product development
new product development
human–computer interaction
3d printing
product design processes
prototyping
product development processes
photometric stereo
depth from focus and defocus
structed light methods
reflectance models
radiometry
epipolar geometry
camera model
camera calibration
structure from motion
simple stereo
epidemic analysis
medical humanities
pandemic policy
public health
epidemiology
network architecture
mobility management
4g technology
acces network security
network interconnection
5g services and architecture
network-access security
services based interfaces and architecture (sbi/sba)
new radio (nr) interface
wireless network
mmwave
industrial iot
massive mimo
5g
video editing
linear editing
video production
video pre-production
communication
empathy and compassion
perspective taking
code refactoring
test-driven development
unit testing
python programming
collaboration
managing stakeholders
resilience
relationships
negotiation
android software development
mobile app
mobile application development
3d computer graphics
virtual reality
sustainable business
critical thinking
sustainable development
anatomy
audio recording
music making
file management
ableton
midi programming
logical controls
administrative controls
physical controls
understand the power of corporate culture
how organizational leaders are ultimately accountable for meeting commitments
how different situations require different decision-making techniques and how to avoid decision bias
techniques to lead change and manage the risks associated with disruption
interpret eps data analyze its implications for investors and other stakeholders identify factors that may impact eps calculations and calculate both basic and diluted eps using relevant financial data
recognize different types of accounting changes e.g. changes in principle estimate and error corrections and demonstrate how to apply retrospective and prospective approaches when dealing with accounting changes
identify and describe the various components of shareholders' equity and be able to interpret and analyze equity-related information in financial statements effectively including the principles and procedures related to share-based compensation
demonstrate the appropriate accounting treatment for deferred tax assets and liabilities
classify cash flow activities into operating investing and financing activities and define the indirect and direct methods of calculating cash flows from operating activities
ability to account for pensions
ability to account for current liabilities and contingencies
ability to classify and record different types of lease arrangements for both the lessee and lessor
ability to analyze and interpret the financial impact of different liability transactions on the financial position and performance of a company
ability to account for long-term debt and bonds
accounting
analytics
earnings management
finance
bookkeeping
financial accounting
unary language
accounting
banking
accounts receivable and cash receipts
inventory costing methods
pp&e accounting
asset accounting
depreciation
data analysis
python programming
machine learning
data visualization (dataviz)
python programming
data visualization (dataviz)
linear regression
sql
data preparation
accounting
mergers and acquisitions (m&a)
taxes
financial statement
accounting
corporate accouting
management accounting
cost accounting
activity based costing
cost
ability to analyze and discuss key financial statements
ability to conceptualize and apply the general approach to revenue recognition and long-term contracts
ability to conceptualize financial accounting structure ad standards
ability to produce financial statements through recognition measurement and reporting
ability to measure variables used in time value of money
gst
stock management
financial accounting
cost and profit
basic computer skills
estimation interview
data analysis interview
strategy interview
behavioral interview
product design interview
acting
literature
textual analysis
theatre
shakespeare
integrative healthcare
wellbeing
patient-centered care
improved symptom management
evidence-based practice
personal advertisement
planning
adaptability
resilience
prevention programs
addiction treatment
brain
drug and alcohol abuse treatment
substance use disorder treatment
substance use disorder prevention
substance use disorder screening
substance use disorder
substance use disorder diagnosis
incorporating electronic components
data-informed decision-making
scope (project management)
business process
teaching
communication
planning
attention deficit hyperactivity disorder (adhd)
apposition
grammar
english language
adjective
accounting organizational skills
ability to prepare financial statements
data analysis
proficiency in accounting software
critical thinking skills
reproducibility
github
r programming
data analysis
informatics
natural language processing
machine learning
bias–variance tradeoff
supply chain
image analysis
python programming
linear programming (lp)
np-completeness
dynamic programming
cloud platforms
cloud applications
kubernetes
cloud computing
input shaped attitude control
time varying geometry
spacecraft simulation
center of mass properties
pricing
strategic management
marketing
competitiveness
salience
image segmentation
model interpretability
class activation maps
tensorflow object detection api
asset management
threat model
cybersecurity strategies
threat mitigation
access control
data model
extraction, transformation and loading (etl)
data warehousing
graphs
search algorithm
graph algorithms
graph data structures
graphs
unsupervised learning
autoencoder
deep learning
tensorflow serving
machine learning
federated learning
tensorflow hub
tensorboard
dashboard (business)
microsoft excel
data virtualization
data visualization (dataviz)
thermoelectric
oxide
ceramics
materials
material engineering
media literacy
communication
multiliteracy
information seeking behavior
critical thinking
architecture development
ui development
statement management
mobile devices
ui animation
artificial neural network
xgboost
tensorflow
tree ensembles
advice for model development
analytics
operations management
linear programming (lp)
mathematical optimization
database (db) design
database (dbms)
mysql
future package technologies
advanced packaging assembly methods
heterogeneous integration
5d and 3d integration methods
ios app development
application development
swift programming
logic programming
r programming
object-oriented programming (oop)
functional programming
unit testing
front-end web development
react (web framework)
database (dbms)
data warehousing
nosql
big data
database administration
essay writing
academic writing
creative writing
writing
training
health equity
bias
public health
leadership development
marketing plan
market analysis
social media marketing
e-commerce
social media marketing
meta ads manager
meta advertising
environmental science
ecology
data visualization (dataviz)
sustainability
research methods
project management
agile management
work management
scrum (software development)
agile software development
scrum methodology
zenhub
kanban
sprint planning
software development
agile management
program evaluation and review technique (pert)
agile software development
coaching
influencing
agile management
problem solving
scrum
software development kit (sdk)
agile software development
scrum (software development)
psychology
research
public health
personal development
machine learning
deep learning
long short-term memory (istm)
apache spark
python programming
conversational ai solutions
azure cognitive services
azure ai solutions: planning and management
nlp solutions
understanding of algorithms
familiarity with predictive models
overview of ethics considersations
python programming
ai for good
air quality monitoring
design frameworks
machine learning fairness
ethics
data bias
customer experience
ai hardware
b2b sales
ai software
ai pipeline
analysis
ethics
artificial intelligence (ai)
bias
ethics of artificial intelligence
whole genome sequencing
machine learning
drug discovery
dimensionality reduction
k-means clustering
workflow of machine learning projects
ai terminology
ai strategy
workflow of data science projects
deep learning
image segmentation
machine learning
model evaluation
multi-class classification
deep learning
machine learning
time-to-event modeling
random forest
model tuning
treatment effect estimation
machine learning interpretation
random forest
natural language entity extraction
question-answering
ethics
machine learning
ethics of artificial intelligence
security
privacy
deep learning
application programming interfaces (api)
artificial intelligence (ai)
machine learning
watson
human resources (hr)
hiring manager training
hiring manager certification
talen acquisition training
communication
identifying performance goals
human resources (hr)
onboarding
leadership development
candidate screening
effective onboarding
resume
interview
recruitment
hiring manager training
hiring manager certification
talent acquisition training
cdn
hypertext transfer protocol (http)
jquery
ajax (programming)
javascript
relational database concepts
organizing data
working with sql queries and functions
manipulating table data
using subqueries
internet protocol (ip) suite
network transmissions and hardware
network theory
network architecture
network management / troubleshooting
performing basic linux tasks
user and group accounts
managing the file system in linux
managing linux permissions and ownership
managing jobs and processes
using databases and interacting with web sites
create user-defined functions
structuring code for reuse
developing a simple application
exploring programming concepts
information security (infosec)
network security
risk management
computer security incident management
mobile security
embedding and linking content
adding animation
using advanced techniques to select and apply styles
formatting content with css
authoring content in html
integrals
derivatives
algebra
matrix algebra
numerical analysis
graph theory
algorithms
python programming
graph algorithms
algorithms
python programming
algorithmic efficiency
dynamic programming
dynamic programming
debugging
software testing
algorithms
computer programming
algorithms
randomized algorithm
sorting algorithm
divide and conquer algorithms
graphs
data structure
algorithms
hash table
spanning tree
algorithms
dynamic programming
greedy algorithm
data structure
algorithms
np-completeness
dynamic programming
graph theory
graphs
graph algorithms
suffix tree
suffix array
knuth–morris–pratt (kmp) algorithm
algorithms on strings
data structure
algorithms
java programming
graphs
data structure
algorithms
data compression
analysis of algorithms
hashtables
algorithm design
python programming
data structure design
cloud computing security
database management
object storage
cloud computing
devops
system operation
alibaba cloud
dietary interventions
macronutrient compositions
diet and exercise alignment
nutrition coaching
energy systems principles
critical thinking
system dynamics
design alternative payment models
implementing
evaluation
design value based payment models
critical thinking
american law
common law
law
constitution
analytical thinking
cultural awareness
polictal knowledge
emotional intelligence
relational skills
stress management
mindfulness
resilience
cryptography
graph theory
logic
cryptography
linear programming (lp)
programming principles
python programming
coding
healthcare systems analysis
forecasting trends
healthcare innovation
using qualitative and quantitative data analysis approaches
analyse and interpret data
business analysis skills and knowledge
management
project management skills and knowledge
lagrangian dynamics
holonomic constraints
d'alembert's principle
hamilton's extended principle
multi-body dynamics
data analysis
business analysis
business analytics
business process
data analysis
tableau software
mysql
sql
iso 9001: 2015
lean
design of experiments (doe)
data-driven decision making
six sigma
binary classification
data analysis
microsoft excel
linear regression
data-informed decision-making
strategic thinking
systems thinking
data analysis
leadership
data management
athlete representation
contract management
operations management
negotiation
data analysis
mysql
teradata
sql
data analysis
tableau software
data visualization (dataviz)
visualization (computer graphics)
spreadsheet
data analysis
sql
data calculations
data aggregation
data insight
data analysis
dissemination
preprocess data
data visualization (dataviz)
anatomy
medicine
dissection
human anatomy
art history
greek mythology
history
ancient greece
animal
marine biology
evolution
paleontology
android studio
kotlin
ux and ui
opengl++
2d computer graphics
opengl for embedded systems (opengl es)
android studio
3d computer graphics
android studio
android (operating system) software
android software development
user interface
interaction technique
list of graphical user interface elements
user interface techniques
android (operating system) software
computer programming
computer programming
android studio
android software development
concurrent computing
animal
animal behavior
veterinary
dog
animal welfare
sociological concepts
animal welfare
sociological concepts
jquery
javascript
animations
calculus
and probability theory
linear algebra
jinja (template engine)
yet another markup language (yaml)
configuration management
network automation
ansible
drug resistance
antimicrobial
genome
microbiology
history of race and racism
talking about race and racism
anti-racism terms
identity
anti-racism
history of race and racism
thinking about race and racism
intersectionality
dialogue
anti-racism
community outreach
history of race and racism
talking about race and racism
global race and racism
anti-racism
data analysis
spark sql
sql
debugging
authentication and authorization
rest apis
filtering and ordering
serializers and deserializers
application deployment
debugging
google cloud
cloud computing
execution environments
computer programming
debugging
manufacturing process management
use case
computer programming
event (computing)
devops
cloud api
numeric operators
logic
python programming
design pattern
computer programming
open web application security project (owasp)
observability
security
monitoring
logging
serverless
microservices
representational state transfer (rest)
openshift
cloud applications
methodology
github
jupyter notebook
data science methodology
k-means clustering
data science
machine learning
databricks
pix2pix
image-to-image translation
cyclegans
convolutional neural network
privacy preservation
natural language processing
robotic process automation
analytics
data analysis
accounting analytics
marketing
regression
analytics
data analysis
marketing analytics
quality management
stakeholder management
problem solving
effective communication
project management
requirements analysis
reliability engineering
design reviews
systems engineering
functional analysis
change management
appreciative inquiry
positive psychology
facilitation
energy
energy level
perturbation theory
quantum mechanics
economics
public policy
policymaking
governance
job interviews
communication
networking
resume writing
nonverbal communication
win-win game
negotiation
planning
principled negotiation
tensorflow
machine learning
cloud computing
artificial intelligence (ai)
machine learning
design thinking
business applications
computational creativity
artificial intelligence (ai)
machine learning
thinking skills
ethical awareness
design thinking
artificial intelligence (ai)
microsoft azure
predictive analytics
analytics
decision support system
workflow
fundraising
customer relationship management (crm)
management
marketing
cloud platforms
cloud api
google cloud platform
network security
microsoft azure
cloud platforms
cloud computing
network management
aruba netedit
network configuration
network management
aruba switching
stacking technologies
wireless network
wlan architecture
w-fi standards
radio frequency (rf)
python programming
representational state transfer (rest)
network automation
computer network
ansible
hashing
authentication
cryptography
network security
malware
routing & gateways
switching
wired networking
aruba
networking layers
asian-american identity
asian-american history
intersectionality
stereotypes and representation
anti-racism
spreadsheet
questioning
decision-making
problem solving
data analysis
data structure
algorithms
algorithm design
string (computer science)
digital marketing kpis
spreadsheet management
presenting to stakeholders
media planning and strategies
marketing analytics
disease
community health
health indicator
patient
recognizing reactions to conflict
identifying the nature of conflict
listening actively for interests
asking questions
diversity and inclusion
unconscious bias recognition
business case
recruitment
make informed decisions and assessments regarding financial statements and the overall financial health of an organization
determine the appropriate classification measure and disclosure of major asset categories
measure and report issues related to inventories long-lived assets and pp&e
identify and account for debt and equity investments
vulnerability assessment
threat analysis
authentication
cryptography
asset classification
association rule learning
fp growth
apriori
outlier
frequent patterns
solar systems
chemistry
theory of relativity
astrobiology
biology
solar systems
microbiology
astrobiology
essay writing
financing your education
interviewing
intentional decision-making
reformer models
neural machine translation
chatterbot
t5+bert models
attention models
variable speed control moment gyroscopes
control moment gyroscopes (cmgs)
nonlinear attitude control
rw performance envelopes
reaction wheels
website structure
customer awareness
google
search engine marketing
search engine optimization (seo)
diversity and inclusion
unconscious bias recognition
business case
recruitment
digital signal processing
signal processing
python programming
fft algorithms
autocad
design
autodesk
engineering
computer-aided design (cad)
city planning
autodesk civil 3d
civil engineering
engineering
mechanical design
autodesk
engineering
computer-aided design (cad)
inventor
autodesk
engineering
computer-aided design (cad)

In [28]:
df_exploded2 = df_exploded.copy()
df_exploded2['skills'] = temp

display(df_exploded2)

,url,name,topics,skills,description,language,outcomes
0,https://www.coursera.org/learn/ibm-cyber-threa...,Cyber Threat Intelligence | Coursera,"[Information Technology, Security]",application security,This course gives you the background needed to...,English,[]
0,https://www.coursera.org/learn/ibm-cyber-threa...,Cyber Threat Intelligence | Coursera,"[Information Technology, Security]",threat intelligence,This course gives you the background needed to...,English,[]
0,https://www.coursera.org/learn/ibm-cyber-threa...,Cyber Threat Intelligence | Coursera,"[Information Technology, Security]",network defensive tactics,This course gives you the background needed to...,English,[]
0,https://www.coursera.org/learn/ibm-cyber-threa...,Cyber Threat Intelligence | Coursera,"[Information Technology, Security]",security analyst,This course gives you the background needed to...,English,[]
0,https://www.coursera.org/learn/ibm-cyber-threa...,Cyber Threat Intelligence | Coursera,"[Information Technology, Security]",cybersecurity,This course gives you the background needed to...,English,[]
...,...,...,...,...,...,...,...
5263,https://www.coursera.org/learn/zn-and-ni-based...,Zn and Ni Based Batteries | Coursera,"[Physical Science and Engineering, Electrical ...",battery types,Zn and Ni based Batteries: This course focuses...,English,"[ Participants will learn active materials, ch..."
5263,https://www.coursera.org/learn/zn-and-ni-based...,Zn and Ni Based Batteries | Coursera,"[Physical Science and Engineering, Electrical ...",battery charging,Zn and Ni based Batteries: This course focuses...,English,"[ Participants will learn active materials, ch..."
5264,https://www.coursera.org/learn/zos-rexx-progra...,IBM z/OS Rexx Programming | Coursera,"[Computer Science, Software Development]",computer programming,This course is designed to teach you the basic...,English,"[Write programs using REXX, Create user-define..."
5264,https://www.coursera.org/learn/zos-rexx-progra...,IBM z/OS Rexx Programming | Coursera,"[Computer Science, Software Development]",mainframe coding,This course is designed to teach you the basic...,English,"[Write programs using REXX, Create user-define..."
5264,https://www.coursera.org/learn/zos-rexx-progra...,IBM z/OS Rexx Programming | Coursera,"[Computer Science, Software Development]",rexx,This course is designed to teach you the basic...,English,"[Write programs using REXX, Create user-define..."

In [38]:
df_exploded2 = df_exploded2.rename(columns={"skills": "skills_title"})
display(df_exploded2)

,url,name,topics,skills_title,description,language,outcomes
0,https://www.coursera.org/learn/ibm-cyber-threa...,Cyber Threat Intelligence | Coursera,"[Information Technology, Security]",application security,This course gives you the background needed to...,English,[]
0,https://www.coursera.org/learn/ibm-cyber-threa...,Cyber Threat Intelligence | Coursera,"[Information Technology, Security]",threat intelligence,This course gives you the background needed to...,English,[]
0,https://www.coursera.org/learn/ibm-cyber-threa...,Cyber Threat Intelligence | Coursera,"[Information Technology, Security]",network defensive tactics,This course gives you the background needed to...,English,[]
0,https://www.coursera.org/learn/ibm-cyber-threa...,Cyber Threat Intelligence | Coursera,"[Information Technology, Security]",security analyst,This course gives you the background needed to...,English,[]
0,https://www.coursera.org/learn/ibm-cyber-threa...,Cyber Threat Intelligence | Coursera,"[Information Technology, Security]",cybersecurity,This course gives you the background needed to...,English,[]
...,...,...,...,...,...,...,...
5263,https://www.coursera.org/learn/zn-and-ni-based...,Zn and Ni Based Batteries | Coursera,"[Physical Science and Engineering, Electrical ...",battery types,Zn and Ni based Batteries: This course focuses...,English,"[ Participants will learn active materials, ch..."
5263,https://www.coursera.org/learn/zn-and-ni-based...,Zn and Ni Based Batteries | Coursera,"[Physical Science and Engineering, Electrical ...",battery charging,Zn and Ni based Batteries: This course focuses...,English,"[ Participants will learn active materials, ch..."
5264,https://www.coursera.org/learn/zos-rexx-progra...,IBM z/OS Rexx Programming | Coursera,"[Computer Science, Software Development]",computer programming,This course is designed to teach you the basic...,English,"[Write programs using REXX, Create user-define..."
5264,https://www.coursera.org/learn/zos-rexx-progra...,IBM z/OS Rexx Programming | Coursera,"[Computer Science, Software Development]",mainframe coding,This course is designed to teach you the basic...,English,"[Write programs using REXX, Create user-define..."
5264,https://www.coursera.org/learn/zos-rexx-progra...,IBM z/OS Rexx Programming | Coursera,"[Computer Science, Software Development]",rexx,This course is designed to teach you the basic...,English,"[Write programs using REXX, Create user-define..."

In [39]:
import csv
from pathlib import Path

formato =[".csv", ".tsv"] 

OUT_DIR2 = Path("results")
OUT_DIR2.mkdir(parents=True, exist_ok=True)

for i in formato:
    df_exploded2.to_csv(f"{OUT_DIR2}/courses_full{i}", index=False, encoding="utf-8",
                        quoting=csv.QUOTE_MINIMAL, quotechar='"', escapechar='\\')

## Skills

In [41]:
conteo = pd.DataFrame(df_exploded2["skills_title"].value_counts())

display(conteo)

                                                    count
skills_title
data analysis                                         170
python programming                                    160
machine learning                                      117
communication                                         106
data visualization (dataviz)                           83
...                                                   ...
triboelectric                                           1
designing and redesigning energy systems to put...      1
recognizing energy injustice                            1
applying concepts and tools to advance energy j...      1
rexx                                                    1

[5304 rows x 1 columns]

In [44]:
skills = pd.DataFrame(df_exploded2["skills_title"].unique(), 
                        columns=["skill_title"]
                        )
display(skills)

                    skill_title
0          application security
1           threat intelligence
2     network defensive tactics
3              security analyst
4                 cybersecurity
...                         ...
5299                     panels
5300                        tso
5301                      sysop
5302           mainframe coding
5303                       rexx

[5304 rows x 1 columns]

In [ ]:
# skills = skills.rename(columns={"skills": "skills_title"})
# display(skills)

                              0
0          application security
1           threat intelligence
2     network defensive tactics
3              security analyst
4                 cybersecurity
...                         ...
5299                     panels
5300                        tso
5301                      sysop
5302           mainframe coding
5303                       rexx

[5304 rows x 1 columns]

In [45]:
for i in formato:
    skills.to_csv(f"{OUT_DIR2}/courses_plain{i}", index=False, encoding="utf-8",
                        quoting=csv.QUOTE_MINIMAL, quotechar='"', escapechar='\\')